planning_plugin: ompl_interface/OMPLPlanner

request_adapters: >-
  default_planner_request_adapters/AddTimeOptimalParameterization
  default_planner_request_adapters/ResolveConstraintFrames
  default_planner_request_adapters/FixWorkspaceBounds
  default_planner_request_adapters/FixStartStateBounds
  default_planner_request_adapters/FixStartStateCollision
  default_planner_request_adapters/FixStartStatePathConstraints

start_state_max_bounds_error: 0.1

planner_configs:
  RRTConnectkConfigDefault:
    type: geometric::RRTConnect
    range: 0.0
  RRTkConfigDefault:
    type: geometric::RRT
    range: 0.0
    goal_bias: 0.05
  RRTstarkConfigDefault:
    type: geometric::RRTstar
    range: 0.0
    goal_bias: 0.05
    delay_collision_checking: 1
  PRMkConfigDefault:
    type: geometric::PRM
    max_nearest_neighbors: 10
  PRMstarkConfigDefault:
    type: geometric::PRMstar
  ESTkConfigDefault:
    type: geometric::EST
    range: 0.0
    goal_bias: 0.05
  TRRTkConfigDefault:
    type: geometric::TRRT
    range: 0.0
    goal_bias: 0.05

robot_manipulator:
  planner_configs:
    - RRTConnectkConfigDefault
    - RRTkConfigDefault
    - RRTstarkConfigDefault
    - PRMkConfigDefault
    - PRMstarkConfigDefault
    - ESTkConfigDefault
    - TRRTkConfigDefault
  projection_evaluator: joints(joint1,joint2)
  longest_valid_segment_fraction: 0.005
