# Configuration file for Beckhoff EL3104
vendor_id: 0x00100000
product_id: 0x10f41001

rpdo:
  - index: 0x1601
    channels:
      - {index: 0x7000, sub_index: 1, type: int8, command_interface: d_output_allbit}

tpdo:

  - index: 0x1A01
    channels:
      - {index: 0x6000, sub_index: 1, type: int8,  state_interface: d_input_allbit}

  - index: 0x1A04
    channels:
      - {index: 0xa000, sub_index: 1, type: int16, state_interface: error_code}
      
      