name: gsc1
owner: adnan
description: this is very first project ever created in the history of gsc private limited.
project_type: standard
created_at: '2026-08-24T10:26:46.225Z'
version: 1.0.0
project_version: 1.0.0
